#!/bin/bash

##
# this script will retrieve secrets from AWS parameter store
# then it will replace specific attribute's existing values with secret values like db url, db name and db credentials
# in jenkins pipeline this script will run after checking out to the specific git branch and before starting the build
# so that we may get the accurate information in the build artifact
##

set -ex

DB_URL=$(aws ssm get-parameters --region us-east-2 --names VAR_URL --query Parameters[0].Value | tr -d \")
DB_NAME=$(aws ssm get-parameters --region us-east-2 --names VAR_DATABASE_NAME --query Parameters[0].Value | tr -d \")
DB_USER=$(aws ssm get-parameters --region us-east-2 --names VAR_DATABASE_USERNAME --query Parameters[0].Value | tr -d \")
DB_PW=$(aws ssm get-parameters --region us-east-2 --names VAR_DATABASE_PASSWORD --query Parameters[0].Value | tr -d \")
URL=$(printf "jdbc:postgresql://%s/%s" "${DB_URL}" "${DB_NAME}")

LINE_USER=$(grep -nw username file.yml | head -n 1 | awk {'print $1'} | tr -d \:)
LINE_PW=$(grep -nw password file.yml | head -n 1 | awk {'print $1'} | tr -d \:)
LINE_URL=$(grep -nw url file.yml | head -n 1 | awk {'print $1'} | tr -d \:)

sed -i "${LINE_USER}s%username: .*$%username: ${DB_USER}%" file.yml
sed -i "${LINE_PW}s%password: .*$%password: ${DB_PW}%" file.yml
sed -i "${LINE_URL}s%url: .*$%url: ${URL}%" file.yml
