version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 2.2
  pre_build:
    commands:
      - echo "using buildspec.yml from branch"
  post_build:
    commands:
      - echo "build is finished"
