#!/usr/bin/env groovy

import jenkins.model.*

node {
  stage('Build') {
    awsCodeBuild projectName: "testJenkinsCB", region: "us-west-2", sourceControlType: "project", credentialsId: "CodeBuild_AWS_ID", credentialsType: "jenkins"
  }
}

